services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "51212:51212"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      WATCHPACK_POLLING: "true"
      NODE_ENV: development
    command: sh -c "npx prisma generate && npm run dev -- --hostname 0.0.0.0"
    restart: unless-stopped
